Repository SM-137/SM-137-Frontend, pull requests merged in 2024-11, with the labels that each got.

#2 Feat : Header 컴포넌트 제작
  @types/svg.d.ts
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/logo/logo-light.svg
  src/assets/icons/logo/logo.svg
  src/components/header/Header.tsx
  src/index.css
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: 🖌️ Design, ✨ Feat

#3 Feat : 말풍선 컴포넌트 (헤더 네비게이터, 알람 말풍선) 제작
  .gitignore
  eslint.config.js
  eslintrc.json
  index.html
  package-lock.json
  package.json
  prettierrc.json
  public/.DS_Store
  src/.DS_Store
  src/App.tsx
  src/assets/.DS_Store
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/components/1.txt
  src/components/button/Button.tsx
  src/components/content-bubble/ContentBubble.tsx
  src/components/content-bubble/contents/HeaderNavigator.tsx
  src/components/content-bubble/contents/Notification.tsx
  src/components/info-message/InfoMessage.tsx
  src/hooks/1.txt
  src/index.css
  src/main.tsx
  src/pages/1.txt
  src/reset.css
  src/styles/1.txt
  src/utils/InfoMessageUtils.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🖌️ Design, ✨ Feat

#4 Feat : QuickLink 컴포넌트 제작
  src/App.tsx
  src/components/quick-link/QuickLink.tsx
Labels: 🖌️ Design, ✨ Feat

#5 Feat : 프로그래스바 컴포넌트 제작
  src/App.tsx
  src/components/progress-line/IconWithText.tsx
  src/components/progress-line/ProgressBar.tsx
Labels: 🖌️ Design, ✨ Feat

#6 Feat : 사이드 네비게이터 컴포넌트 제작
  src/App.tsx
  src/assets/symbol_Color.png
  src/components/side-navigator/SideNavigator.tsx
  src/components/side-navigator/UserInfo.tsx
Labels: 🖌️ Design, ✨ Feat

#10 Feat : (PillButton) 알약 모양 버튼 컴포넌트 제작
  src/App.tsx
  src/components/pill-button/PillButton.tsx
Labels: 🖌️ Design, ✨ Feat

#12 Feat : 카테고리 태그 컴포넌트 구현 (해시태그 역할)
  src/App.tsx
  src/components/category-tag/CategoryTag.tsx
  src/components/category-tag/CategoryTagGroup.tsx
Labels: 🖌️ Design, ✨ Feat

#14 Refactor, Feat, Design : 헤더-사이드 네비게이터-알림창 연결 / 모바일 반응형 구현
  src/App.tsx
  src/components/.DS_Store
  src/components/content-bubble/ContentBubble.tsx
  src/components/content-bubble/contents/HeaderNavigator.tsx
  src/components/header/.DS_Store
  src/components/header/Connect.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderProvider.tsx
  src/components/header/header-components/HeaderMyPage.tsx
  src/components/header/header-components/HeaderNotify.tsx
  src/components/header/header-components/HeaderSideNav.tsx
  src/components/side-navigator/SideNavigator.tsx
  src/components/side-navigator/UserInfo.tsx
  src/contexts/HeaderOpenContext.tsx
  src/pages/SideNavConnect.tsx
  src/styles/1.txt
  src/styles/HeaderIconStyle.ts
Labels: 🖌️ Design, ✨ Feat, 🛠️ Refactor

#16 Feat : 서치바 컴포넌트 제작
  src/App.tsx
  src/components/button/Button.tsx
  src/components/form/UserInfoForm.tsx
  src/components/info-message/InfoMessage.tsx
  src/components/input/Input.tsx
  src/components/modal/Modal.tsx
  src/components/modal/contents/InitialInfo.tsx
  src/components/search-bar/SearchBar.tsx
  src/components/search-bar/SearchButton.tsx
  src/components/search-bar/SearchInput.tsx
  src/index.css
  src/reset.css
Labels: 🖌️ Design, ✨ Feat

#18 Feat : ContentBox / ContentList 컴포넌트 제작 (민원글 출력형식)
  .gitignore
  src/App.tsx
  src/components/content/ContentBox.tsx
  src/components/content/ContentList.tsx
  src/components/interaction/Interaction.tsx
  src/components/interaction/InteractionGroup.tsx
  src/components/status-button/StatusButton.tsx
  src/components/status-button/StatusDisplay.tsx
  src/index.css
  src/styles/ContentStyle.ts
Labels: 🖌️ Design, ✨ Feat

#19 Feat: 버튼 컴포넌트 제작
  src/App.tsx
  src/components/button/Button.tsx
  src/components/button/ButtonType.ts
Labels: 🖌️ Design, ✨ Feat, 🛠️ Refactor

#21 fix : contentBox 요소가 화면과 다르게 보이는 오류 해결
  src/App.tsx
  src/components/category-tag/CategoryTag.tsx
  src/components/content/ContentBox.tsx
  src/components/interaction/Interaction.tsx
Labels: 🛠️ Fix

#24 Feat : Home 페이지 제작
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/assets/emblem-1_DarkGray.png
  src/components/button/Button.tsx
  src/components/content-bubble/contents/HeaderNavigator.tsx
  src/components/content/ContentBox.tsx
  src/components/content/ContentList.tsx
  src/components/hashtag-cloud/HashtagCloud.tsx
  src/components/header/Connect.tsx
  src/components/header/Header.tsx
  src/components/quick-link/QuickLink.tsx
  src/components/quick-link/QuickLinkItem.tsx
  src/components/search-bar/SearchInput.tsx
  src/components/status-button/StatusButton.tsx
  src/components/status-button/StatusButtonGroup.tsx
  src/components/status-button/StatusDisplay.tsx
  src/contexts/HeaderOpenContext.tsx
  src/mockData.ts
  src/pages/1.txt
  src/pages/Layout.tsx
  src/pages/SideNavConnect.tsx
  src/pages/home/Home.tsx
  src/pages/home/HomeContentList.tsx
  src/styles/ContentStyle.ts
  src/types/Type.ts
Labels: 🖌️ Design, ✨ Feat

#23 Feat: 추천해시태그 창 제작
  src/App.tsx
  src/components/pill-button/PillButton.tsx
  src/components/rec-hashtag/RecHashTag.tsx
Labels: 🖌️ Design, ✨ Feat

#22 Feat : Interaction Button에 애니메이션 설정
  src/components/interaction/Interaction.tsx
Labels: 🖌️ Design, ✨ Feat

#17 Feat : 카테고리 선택창 컴포넌트 제작
  src/App.tsx
  src/components/.DS_Store
  src/components/button/Button.tsx
  src/components/button/ButtonType.ts
  src/components/category-select/CategorySelect.tsx
  src/components/category-select/SubCategory.tsx
  src/utils/SubCategoryContent.ts
Labels: 🖌️ Design, ✨ Feat
