Repository SM-137/SM-137-Frontend, pull requests merged in 2025-01, with the labels that each got.

#31 Feat : API 호출 코드 작성
  .gitignore
  package-lock.json
  package.json
  src/services/apiClient.ts
  src/services/complaintService.ts
  src/services/userService.ts
  src/types/Type.ts
  vite.config.ts
Labels: ✨ Feat

#33 Feat : 민원 답변 컴포넌트 제작
  .env
  src/Router.tsx
  src/components/answer/Answer.tsx
  src/components/comment/CommentInput.tsx
  src/mockData.ts
  src/pages/detail/Detail.tsx
  src/pages/search/Search.tsx
  src/types/Type.ts
Labels: 🖌️ Design, ✨ Feat

#34 Feat : 로딩컴포넌트 레이아웃 제작
  src/assets/icons/spinner.gif
  src/components/loading/Loading.tsx
Labels: 🖌️ Design, ✨ Feat

#36 Feat : 마이페이지 화면 제작
  src/Router.tsx
  src/assets/icons/gmail.png
  src/components/category-tag/CategoryTag.tsx
  src/components/comment/Comment.tsx
  src/components/content-bubble/contents/Notification.tsx
  src/mockData.ts
  src/pages/my-page/MyComplaints.tsx
  src/pages/my-page/MyPage.tsx
  src/pages/my-page/MyPageAlarm.tsx
  src/pages/my-page/MyPageInfo.tsx
  src/pages/my-page/ScrapComplaints.tsx
  src/styles/ContentViewStyle.ts
  src/types/Type.ts
Labels: 🖌️ Design, ✨ Feat

#35 Feat : 내 민원 페이지 제작
  src/Router.tsx
  src/components/input/Input.tsx
  src/pages/my-complaint/Complaint.tsx
  src/pages/my-complaint/ComplaintFilterBar.tsx
  src/pages/scrap/Scrap.tsx
  src/pages/scrap/ScrapList.tsx
Labels: 🖌️ Design, ✨ Feat

#41 Fix, Feat : 라우팅에 따른 로고 렌더링 오류 해결 및 화면 라우팅 추가
  src/components/content-bubble/contents/HeaderNavigator.tsx
  src/components/content-bubble/contents/Notification.tsx
  src/components/header/.DS_Store
  src/components/header/Header.tsx
  src/components/search-bar/SearchBar.tsx
  src/components/search-bar/SearchButton.tsx
  src/components/search-bar/SearchInput.tsx
  src/components/side-navigator/SideNavigator.tsx
  src/contexts/HeaderOpenContext.tsx
  src/pages/search/Search.tsx
  src/utils/URL.ts
Labels: 🛠️ Fix, ✨ Feat

#38 Feat : 스크랩한 민원 페이지 제작
  src/Router.tsx
  src/pages/scrap/Scrap.tsx
  src/pages/scrap/ScrapList.tsx
  src/styles/ComplaintScrap.ts
Labels: 🖌️ Design, ✨ Feat

#46 Feat : 학적정보 확인 폼 페이지 제작
  src/components/check-box/CheckBox.tsx
  src/components/form/AcademicInfoForm.tsx
  src/pages/application-step/AcademicInfoStep.tsx
Labels: 🖌️ Design, ✨ Feat

#47 Feat : 해시태그 필터링 기능 제작
  src/components/search-filter/HashtagSearch.tsx
  src/components/search-filter/SearchFilter.tsx
  src/hooks/useFilter.ts
  src/utils/HashtagContents.ts
Labels: ✨ Feat

#50 Feat: 내민원 페이지 제작
  dist/_redirects
  dist/assets/emblem-1_DarkGray-Cv6FiteB.png
  dist/assets/gmail-DzyJWfjK.png
  dist/assets/index-Bv40NjP_.js
  dist/assets/symbol_Color-D3CwYGBh.png
  dist/logo.svg
  src/Router.tsx
  src/components/status-button/StatusButtonGroup.tsx
  src/pages/my-complaint/Complaint.tsx
  src/pages/my-complaint/ComplaintFilterBar.tsx
  src/styles/MyPageComplaintStyle.ts
Labels: 🖌️ Design, ✨ Feat

#40 Feat : 민원신청 폼 작성 단계 페이지 제작
  src/pages/application-step/ApplicationStepLayout.tsx
  src/pages/application-step/CompaintsWrittingStep.tsx
Labels: 🖌️ Design, ✨ Feat

#48 Feat: 민원 신청 완료 페이지 제작
  src/components/form/CompletedForm.tsx
  src/pages/application-step/CompletedStep.tsx
Labels: 🖌️ Design, ✨ Feat

#51 Feat: 민원신청 카테고리 선택 페이지 제작
  src/Router.tsx
  src/components/category-select/CategorySelect.tsx
  src/components/category-select/SubCategory.tsx
  src/components/quick-link/QuickLink.tsx
  src/pages/application-step/CategorySelectionStep.tsx
  src/utils/URL.ts
Labels: 🖌️ Design, ✨ Feat

#53 Feat : 전체민원조회/검색조회 페이지네이션 연결
  src/components/Pagination.tsx
  src/components/category-select/SubCategory.tsx
  src/hooks/usePagination.ts
  src/mockData.ts
  src/pages/search/Search.tsx
  src/pages/view/View.tsx
Labels: ✨ Feat

#57 Feat : JWT 토큰 처리 및 민원 신청 첨부파일 기능 수정
  .env
  index.html
  package-lock.json
  package.json
  src/.DS_Store
  src/Router.tsx
  src/assets/google-login.svg
  src/assets/icons/logo/logo-bubble.svg
  src/components/file-upload/FileUploadField.tsx
  src/components/form/ComplaintsForm.tsx
  src/pages/login/Login.tsx
  src/pages/login/LoginTitle.tsx
  src/pages/login/Redirect.tsx
  src/services/apiClient.ts
  src/services/complaintService.ts
  src/services/userService.ts
  src/types/Type.ts
  src/utils/Cookie.ts
Labels: ✨ Feat

#58 Feat : 로그인 리디렉션 기능
  dist/assets.json
  dist/assets/index-B8fAAlkx.js
  dist/assets/index-Bv40NjP_.js
  dist/assets/index-C6ykru3x.js
  dist/assets/index-Cggs9tqo.js
  dist/assets/spinner-CmXwfpV0.gif
  dist/client/404.html
  dist/client/assets/chunks/chunk-XhNS7_By.js
  dist/client/assets/entries/entry-client-routing.B_H6CoQb.js
  dist/client/assets/entries/entry-server-routing.DWqiBHZl.js
  dist/client/assets/entries/src_pages_detail_Detail.page.DHAguQqq.js
  dist/client/logo.svg
  dist/client/preview.png
  dist/index.html
  dist/server/entries/src_pages_detail_Detail-page.mjs
  dist/server/entry.mjs
  dist/server/package.json
  src/Router.tsx
  src/components/PrivateRoute.tsx
  src/components/content/ContentBox.tsx
  src/components/content/ContentList.tsx
  src/components/status-button/StatusButton.tsx
  src/components/status-button/StatusButtonGroup.tsx
  src/components/status-button/StatusDisplay.tsx
  src/hooks/useFilter.ts
  src/hooks/useSort.ts
  src/mockData.ts
  src/pages/home/Home.tsx
  src/pages/home/HomeContentList.tsx
  src/pages/my-complaint/Complaint.tsx
  src/pages/my-page/MyComplaints.tsx
  src/pages/my-page/ScrapComplaints.tsx
  src/pages/scrap/Scrap.tsx
  src/pages/search/Search.tsx
  src/pages/view/View.tsx
  src/services/apiClient.ts
  src/services/complaintService.ts
  src/services/userService.ts
  src/types/Type.ts
  src/utils/URL.ts
  tsconfig.tsbuildinfo
Labels: ✨ Feat

#54 Feat: 마이페이지 더보기에 라우터 연결
  src/Router.tsx
  src/pages/my-page/MyComplaints.tsx
  src/pages/my-page/ScrapComplaints.tsx
  vite.config.ts
Labels: 🖌️ Design

#55 Feat : 개인정보 수정 화면
  src/Router.tsx
  src/assets/gmail.png
  src/components/form/UserInfoForm.tsx
  src/components/input/Input.tsx
  src/pages/modify/Modify.tsx
  src/pages/modify/ModifyForm.tsx
  src/types/Type.ts
  src/utils/MajorList.ts
  vite.config.ts
Labels: 🖌️ Design

#49 Feat: 민원 신청 해시태그 선택 모달창 컴포넌트 제작(수정 중)
  src/components/modal/contents/HashTagInfo.tsx
Labels: 🖌️ Design, ✨ Feat

#61 Feat : complaint service 연동 코드 작성 / 첨부파일 View
  dist/_redirects
  dist/assets/index-D7sIRt7Z.js
  dist/assets/index-DlBAWafV.js
  dist/index.html
  src/DefaulatData.ts
  src/components/answer/Answer.tsx
  src/components/comment/Comment.tsx
  src/components/comment/CommentInput.tsx
  src/components/content/ComplaintContent.tsx
  src/components/content/ContentBox.tsx
  src/components/content/ContentImage.tsx
  src/components/content/ContentList.tsx
  src/components/interaction/Interaction.tsx
  src/components/interaction/InteractionGroup.tsx
  src/components/modal/Modal.tsx
  src/hooks/useFilter.ts
  src/hooks/useSort.ts
  src/mockData.ts
  src/pages/detail/Detail.tsx
  src/pages/view/View.tsx
  src/services/complaintService.ts
  src/types/Type.ts
  tsconfig.tsbuildinfo
Labels: ✨ Feat

#59 Fix: 민원신청 기능 (작성된 기록 저장 / 유효성 검사)
  dist/assets/index-BidAtDMO.css
  dist/assets/index-CEi5CB_6.css
  dist/assets/index-CR-d3FTE.js
  dist/assets/index-D7sIRt7Z.js
  dist/index.html
  package-lock.json
  package.json
  src/Router.tsx
  src/components/academic-info/AcademicInfoForm.tsx
  src/components/alert/Alert.tsx
  src/components/button/Button.tsx
  src/components/category-select/CategorySelect.tsx
  src/components/category-select/SubCategory.tsx
  src/components/check-box/CheckBox.tsx
  src/components/comment/CommentInput.tsx
  src/components/content/ComplaintContent.tsx
  src/components/content/ContentBox.tsx
  src/components/content/ContentList.tsx
  src/components/file-upload/FileUploadField.tsx
  src/components/form/AcademicInfoForm.tsx
  src/components/form/ComplaintsForm.tsx
  src/components/form/CompletedForm.tsx
  src/components/input/TextArea.tsx
  src/components/modal/contents/DeleteComment.tsx
  src/components/modal/contents/HashTagInfo.tsx
  src/components/modal/contents/InitialInfo.tsx
  src/components/modal/contents/Submit.tsx
  src/components/pill-button/PillButton.tsx
  src/components/progress-line/ProgressBar.tsx
  src/components/rec-hashtag/RecHashTag.tsx
  src/index.css
  src/pages/application-step/AcademicInfoStep.tsx
  src/pages/application-step/CategorySelectionStep.tsx
  src/pages/application-step/CompaintsWrittingStep.tsx
  src/pages/application-step/CompletedStep.tsx
  src/pages/complaint-apply/ApplicationLayout.tsx
  src/pages/complaint-apply/CompletedStep.tsx
  src/pages/complaint-apply/apply-step/AcademicInfoStep.tsx
  src/pages/complaint-apply/apply-step/CategorySelectionStep.tsx
  src/pages/complaint-apply/apply-step/CompaintsWrittingStep.tsx
  src/pages/home/HomeContentList.tsx
  src/pages/modify/Modify.tsx
  src/reset.css
  src/services/complaintService.ts
  src/services/hashtagService.ts
  src/services/userService.ts
  src/store/useComplaintStore.ts
  src/styles/AlertStyles.ts
  src/styles/ApplyStyles.ts
  src/types/Type.ts
  src/utils/URL.ts
  tsconfig.tsbuildinfo
Labels: ✨ Feat

#64 Feat: 홈화면 모달창 제어
  src/components/form/UserInfoForm.tsx
  src/components/modal/Modal.tsx
  src/components/modal/contents/InitialInfo.tsx
  src/pages/home/Home.tsx
Labels: ✨ Feat

#67 Feat, Refactor : 민원 이전 단계 렌더링 및 페이지를 벗어날 경우 경고 기능
  src/components/category-select/CategorySelect.tsx
  src/components/category-select/SubCategory.tsx
  src/components/check-box/CheckBox.tsx
  src/components/file-upload/FileUploadField.tsx
  src/components/form/ComplaintsForm.tsx
  src/components/input/Input.tsx
  src/components/input/TextArea.tsx
  src/components/rec-hashtag/RecHashTag.tsx
  src/hooks/ usePrompt.ts
  src/pages/Layout.tsx
  src/pages/complaint-apply/ApplicationLayout.tsx
  src/pages/complaint-apply/apply-step/AcademicInfoStep.tsx
  src/pages/complaint-apply/apply-step/CategorySelectionStep.tsx
  src/store/useComplaintStore.ts
  src/types/Type.ts
  src/utils/SessionStorage.ts
Labels: ✨ Feat, 🛠️ Refactor

#68 Feat : 회원 탈퇴 기능 연동
  dist/assets/index-B487psbr.js
  src/pages/modify/Modify.tsx
  src/services/userService.ts
Labels: ✨ Feat

#69 Feat : 민원 수정 기능 연동
  src/Router.tsx
  src/components/content/ComplaintContent.tsx
  src/components/form/ComplaintsForm.tsx
  src/components/modal/contents/ModifyComments.tsx
  src/components/status-button/StatusButton.tsx
  src/pages/complaint-modify/ComplaintModify.tsx
  src/pages/detail/Detail.tsx
  src/services/complaintService.ts
  src/styles/AlertStyles.ts
Labels: ✨ Feat
